### ISSUE TITLE
Requesting spi recovery image for Gameforce Chi

### ISSUE THREAD

**Issue by Ntemis** [wincao618/gameforce-uboot#1]
Hello,
I went ahead and flashed hardkernel spi recovery image v1.4 and now gameforge is ruined.
Can you please help me and other users out by offering a ready to flash spi recovery image?
Thank you in advance for the support

**Comment by shantigilbert** [comment]
@Ntemis I think I can help, I have one I compiled recently I just need to get to my computer and I will look for it.
